services:
  - type: web
    name: cpp-code-runner
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p temp
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT